### ISSUE TITLE
cant login with users in casino app 

### ISSUE THREAD

**Issue by vmahindra-c** [rbCAS/CASinoApp#19]
Hi,
I am unable to login with users which i created manually in casino_users table using mysql2 database. it is saying (incorrect username or password).I have changed configuration  in cas.yml and database.yml. 
I am sharing my cas.yml, database.yml and casino_users table:

cas.yml file:

```
defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "CASino"
    footer_text: "Powered by <a href=\"http://rbcas.com/\">CASino</a>"

development:
  <<: *defaults
  authenticators:
       my_company_sql_database:
         authenticator: "ActiveRecord"
         options:
           connection:
             adapter: "mysql2"
             host: "localhost"
             username: "root"
             password: "maheshwari"
             database: "CASinoApp"
           table: "casino_users"
           username_column: "username"
           password_column: "password"
           extra_attributes:
             email: "email_database_column"
             fullname: "displayname_database_column"

test:
  <<: *defaults
  authenticators:
    static:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser:
            password: "foobar123"

production:
  <<: *defaults
  authenticators:
    my_company_ldap:
      authenticator: "LDAP"
      options:
        host: "localhost"
        port: 12445
        base: "dc=users,dc=example.com"
        username_attribute: "uid"
        encryption: "simple_tls"
        extra_attributes:
          email: "mail"
          fullname: "displayname"


database.yml file:

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: CASinoApp
  pool: 5
  username: root
  password: maheshwari
  socket: /var/run/mysqld/mysqld.sock
```
casino_users table:
```
mysql> select * from casino_users;
+----+---------------+----------+-------------------------------------------------------------+---------------------+---------------------+
| id | authenticator | username | extra_attributes                                            | created_at          | updated_at          |
+----+---------------+----------+-------------------------------------------------------------+---------------------+---------------------+
|  1 | vijay         | vijay    | NULL                                                        | NULL                | NULL                |
|  2 | static        | testuser | --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess {}
 | 2015-06-29 10:42:36 | 2015-06-29 12:43:32 |
|  3 | vijay1        | vijay123 | --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess     | 2015-06-30 10:42:36 | 2015-06-29 12:46:32 |
|  4 | vijay2        | vijay123 | --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess {}  | 2015-06-30 10:42:36 | 2015-06-29 12:46:32 |
+----+---------------+----------+-------------------------------------------------------------+---------------------+---------------------+
4 rows in set (0.01 sec)
```
