### ISSUE TITLE
unable to login to users in postgres database with encryted password

### ISSUE THREAD

**Issue by vmahindra-c** [rbCAS/CASinoApp#21]
i have users table in remote db with encrypted password and im trying to login with username and password but i am unable to login using casino 
my users table looks like:

```
 id | legacy_id |      given_name       | family_name |        username         |   phone    | organization_id |                         email                          |                                                        encrypted_password                                                        |    password_salt     | reset_password_token | reset_password_sent_at | sign_in_count |     current_sign_in_at     |      last_sign_in_at       | current_sign_in_ip | last_sign_in_ip | failed_attempts | unlock_token | locked_at | authentication_token | legacy_password |        disabled_at         |         created_at         |         updated_at         |   title    |  first_failed_attempt_at   | must_reset_password | locale | receive_gb_notifications 
----+-----------+-----------------------+-------------+-------------------------+------------+-----------------+--------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+----------------------+----------------------+------------------------+---------------+----------------------------+----------------------------+--------------------+-----------------+-----------------+--------------+-----------+----------------------+-----------------+----------------------------+----------------------------+----------------------------+------------+----------------------------+---------------------+--------+--------------------------
  1 |           | G2 value chain member | demo        | g2_vcm                  |            |             207 | developers+g2_vcm@g2llc.com                            | 1e71b30962383428b78048518b32064f37932d7dbaae724dc83152633ed9c3bd8715aa058ec5176015a66ebd73f15531d0fb61aff40d320cfa80db865062474e | xSD1fLYLL1MesHXzdaGL |                      |                        |             0 |                            |                            |                    |                 |               0 |              |           |                      |                 |                            | 2015-06-25 19:20:21.310871 | 2015-06-25 19:20:21.310871 |            |                            | f                   | en-US  | t
```

An my cas.yml file:

```yaml
defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "CASino"
    footer_text: "Powered by <a href=\"http://rbcas.com/\">CASino</a>"

development:
  <<: *defaults
  authenticators:
    my_company_sql_database:
         authenticator: "ActiveRecord"
         options:
           connection:
             adapter: "postgresql"
             host: "dir-ap01.dev.g2"
             username: "postgres"
             password: "d3vpass"
             database: "directory"
           table: "users"
           username_column: "username"
           password_column: "encrypted_password"
test:
  <<: *defaults
  authenticators:
    static:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser:
            password: "foobar123"

production:
  <<: *defaults
  authenticators:
    my_company_ldap:
      authenticator: "ldap"
      options:
        host: "localhost"
        port: 12445
        base: "dc=users,dc=example.com"
        username_attribute: "uid"
        encryption: "simple_tls"
        extra_attributes:
          email: "mail"
          fullname: "displayname"
```

when i am trying to login with username and password in browser i am getting invalid username and password
