### ISSUE TITLE
unable to login to CASinoApp using external database username and password.

### ISSUE THREAD

**Issue by swetha-nfinity** [rbCAS/CASinoApp#22]
I am unable to login to CASinoApp using external database username and password.
I have enabled the # SQL (ActiveRecord authenticator) in cas.yml file.

Please guide me to resolve this issue. 

Below is the cas.yml
```
development:                                                              
  frontend:                                                               
    sso_name: 'CASino'                                                    
    footer_text: 'Powered by <a href="http://rbcas.com/">CASino</a>'      
  authenticators:                                                     
                                                                          
                             
                                                                          
########################################                                  
# SQL (ActiveRecord authenticator)                                        
########################################                                  
     my_company_sql_database:                                             
       authenticator: "ActiveRecord"                                      
       options:                                                           
         connection:                                                      
           adapter: "mysql2"                                              
           host: "localhost"                                              
           username: "test"                                               
           password: "********"                                           
           database: "externalapp"                                          
         table: "users_data"                                                   
         username_column: "username"                                      
         password_column: "password"      
                      
```
