### ISSUE TITLE
Your login request did not include a valid login ticket.

### ISSUE THREAD

**Issue by kirantpatil** [rbCAS/CASinoApp#4]
I am unable to login to CASinoApp using external database username and password.

Is there a admin password to login to the app and check the user details ?

I have enabled the # SQL (ActiveRecord authenticator) in cas.yml file.

Please guide me to resolve this issue.

**Comment by bnmagat** [comment]
Hi! I'm having the same problem here. I'm new to rails and I've found this CASino very useful with my applications. However, I'm having a problem logging in to CASino. I have an existing database "wiz_common_master" which is connected to my applications for the login.

I think I have migrated CASino successfully in this database since there were these casino__ tables. But I don't know how CASino gets the login username and password from my database.

Here is my database.yml
```
  database: wiz_common_master
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Inhouse2012
  socket: /var/lib/mysql/mysql.sock 
```
And my cas.yml
```
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "CASino"
    footer_text: "Powered by <a href=\"http://rbcas.com/\">CASino</a>"

development:
  <<: *defaults
  authenticators:
    my_company_sql_database:
      authenticator: "ActiveRecord"
      options:
       connection:
        adapter: "mysql2"
        host: "localhost"
        username: "root"
        password: "Inhouse2012"
        database: "wiz_common_master"
       table: "m_logins"
       username_column: "login"
       password_column: "crypted_password"
        extra_attributes:
          employee_id: "m_employee_id"
          login_name: "login" 
```
Here are my database's tables:
```
mysql> show tables;
+----------------------------------+
| Tables_in_wiz_common_master      |
+----------------------------------+
| casino_auth_token_tickets        |
| casino_login_attempts            |
| casino_login_tickets             |
| casino_proxy_granting_tickets    |
| casino_proxy_tickets             |
| casino_service_rules             |
| casino_service_tickets           |
| casino_ticket_granting_tickets   |
| casino_two_factor_authenticators |
| casino_users                     |
| m_calendar_items                 |
| m_calendars                      |
| m_class_users                    |
| m_classes                        |
| m_corporations                   |
| m_employee_histories             |
| m_employees                      |
| m_ic_cards                       |
| m_logins                         |
| m_official_posts                 |
| m_premium_rates                  |
| m_section_users                  |
| m_sections                       |
| m_user_data                      |
| schema_migrations                |
+----------------------------------+
25 rows in set (0.00 sec)
```
And my m_logins table:
```
mysql> desc m_logins;
+------------------+-------------+------+-----+-------------------+----------------+
| Field            | Type        | Null | Key | Default           | Extra          |
+------------------+-------------+------+-----+-------------------+----------------+
| id               | int(11)     | NO   | PRI | NULL              | auto_increment |
| login            | varchar(40) | NO   |     | NULL              |                |
| crypted_password | varchar(40) | YES  |     | NULL              |                |
| salt             | varchar(40) | YES  |     | NULL              |                |
| m_employee_id    | int(11)     | NO   |     | NULL              |                |
| created_by       | int(11)     | YES  |     | NULL              |                |
| created_at       | datetime    | NO   |     | CURRENT_TIMESTAMP |                |
| deleted_by       | int(11)     | YES  |     | NULL              |                |
| deleted_at       | datetime    | YES  |     | NULL              |                |
+------------------+-------------+------+-----+-------------------+----------------+
9 rows in set (0.00 sec)
```
